
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YiCraft.Models
{

using System;
    using System.Collections.Generic;
    
public partial class complaint_infos
{

    public int id { get; set; }

    public string title { get; set; }

    public string complaint { get; set; }

    public string time { get; set; }

    public string author { get; set; }

}

}
